### PR TITLE
Using a basic cache for Device objects

### PR DESCRIPTION
**Pull request by lourd**
`this.devices` is now an Object and Devices are stored as values in it
with their id as the key. Spark.getDevice will now use and update the
cache

### CODE REVIEW

**Comment by lourd** [comment]
@emilyrose any feedback on this?

**Comment by emilyrose** [comment]
@lourd it looks beautiful! Would you please sign our CLA? :smile_cat: 

https://docs.google.com/a/particle.io/forms/d/1_2P-vRKGUFg5bmpcKLHO_qNZWGi5HKYnfrrkd-sbZoA/viewform

Thanks!

**Comment by emilyrose** [comment]
It would be superb if we were able to add a passing test to this as well, but I am happy to do this if you don't have the time.

**Comment by lourd** [comment]
Thanks! CLA is signed. I'll work on getting a test. I'm a little unclear on the pattern y'all have going for tests. If you could give me some basic pointers on what to add to get the test stub I included passing that'd be great.

**Comment by lourd** [comment]
Tests are in, should be good to go!

**Comment by lourd** [comment]
Can we get this in por favor?

**Comment by lourd** [comment]
@emilyrose ?

**Comment by lourd** [comment]
So is this just not gonna happen?

**Comment by emilyrose** [comment]
@lourd I'm hesitant to merge this out of a concern that this will silently break for people who are expecting `this.devices` to be an array. Do you have any ideas on this?

**Comment by lourd** [comment]
You could either bump the major version number to indicate a breaking change, or I could change the code to have the cache be an array. That would be a big performance hit though because then the cache lookup is O(n) instead of O(1)

**Comment by lourd** [comment]
There's also `Spark.listDevices` which still returns them as an array

**Comment by emilyrose** [comment]
@lourd you make a convincing argument!

**Pull request merged**
